site_name: MLTrading Documentation
site_description: ML-powered trading system with feature engineering and deployment automation

theme:
  name: material
  palette:
    primary: blue
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
    - Quick Start: guides/quickstart.md
    - Configuration: guides/configuration.md
    - Deployment: deployment/deployments.md
  - Alert System:
    - Overview: alerts/index.md
  - Architecture:
    - System Overview: architecture/SYSTEM_ARCHITECTURE.md
    - Connection Pool Solution: architecture/CONNECTION_POOL_SOLUTION.md
  - Testing:
    - Manual Tests: testing/regression_test_manual.md
    - Deployment Testing: deployment/TESTING-DEPLOYMENTS.md
  - Troubleshooting:
    - Connection Issues: troubleshooting/TROUBLESHOOTING-CONNECTION-ISSUES.md
    - Database Issues: database/DATABASE_TROUBLESHOOTING.md
  - Database:
    - Schema Overview: database/DATABASE_SCHEMA.md
    - Entity Relationships: database/ENTITY_RELATIONSHIPS.md
    - Operations Guide: database/DATABASE_OPERATIONS.md
    - Performance Optimization: database/FEATURE_TABLE_OPTIMIZATION.md
    - Troubleshooting: database/DATABASE_TROUBLESHOOTING.md
  - API Reference: 
    - API Documentation: api/index.md
  - About: about.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_submodules: true
            show_root_toc_entry: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

docs_dir: docs
site_dir: site

exclude_docs: |
  logs/
  __pycache__/

watch:
  - src/