"""Dashboard configuration module."""

from .constants import (
    CHART_COLORS,
    TIME_RANGE_OPTIONS,
    TIME_RANGE_DAYS,
    DEFAULT_CHART_HEIGHT,
    DEFAULT_TIME_RANGE,
    DEFAULT_SYMBOL,
    MARKET_HOURS,
    DASHBOARD_CONFIG,
    EXTERNAL_STYLESHEETS,
    NAV_ITEMS,
    CARD_STYLE,
    CARD_STYLE_NONE
)

__all__ = [
    'CHART_COLORS',
    'TIME_RANGE_OPTIONS', 
    'TIME_RANGE_DAYS',
    'DEFAULT_CHART_HEIGHT',
    'DEFAULT_TIME_RANGE',
    'DEFAULT_SYMBOL',
    'MARKET_HOURS',
    'DASHBOARD_CONFIG',
    'EXTERNAL_STYLESHEETS',
    'NAV_ITEMS',
    'CARD_STYLE',
    'CARD_STYLE_NONE'
]