# Reference environment file - using existing trading_env conda environment
name: trading_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pyyaml>=6.0.0
    - pytest>=7.4.0
    - psycopg2-binary>=2.9.0 