# Alpaca Trading Configuration
# API credentials are loaded from environment variables for security

alpaca:
  # Paper Trading (Safe for testing)
  paper_trading:
    base_url: "https://paper-api.alpaca.markets"
    # Credentials loaded from environment:
    # ALPACA_PAPER_API_KEY
    # ALPACA_PAPER_SECRET_KEY
    
  # Live Trading (Use only when ready!)
  live_trading:
    base_url: "https://api.alpaca.markets"
    # Credentials loaded from environment:
    # ALPACA_LIVE_API_KEY
    # ALPACA_LIVE_SECRET_KEY

# Trading Settings
trading:
  mode: "paper"              # "paper" or "live" - START WITH PAPER!
  default_order_type: "market"
  default_time_in_force: "day"
  max_order_value: 10000     # Maximum $ per order (safety limit)

# Risk Management
risk:
  max_daily_orders: 10       # Limit orders per day
  max_position_size: 1000    # Max shares per position  
  emergency_stop: false      # Emergency stop all trading