# Deployment Configuration for Dashboard Monitoring
# This file defines which Prefect deployments should be monitored by the dashboard
# 
# FEATURE ENGINEERING LEVELS:
# - Phase 1+2+3: Comprehensive Advanced (90+ features) - Complete ML analysis
#
# DEPLOYMENT PRIORITIES:
# 1. High: Comprehensive feature engineering (every 2h during market) - 90+ features
# 2. Supporting: Data collection (hourly during market)

deployments:
  # Comprehensive Feature Engineering (Phase 1+2+3) - 90+ Features
  comprehensive-feature-engineering-production-subprocess:
    name: "comprehensive-feature-engineering-production-subprocess"
    display_name: "Comprehensive Feature Engineering (90+ Features)"
    description: "Production comprehensive feature engineering (Phase 1+2+3) with subprocess isolation - runs every 2 hours for complete feature sets"
    category: "advanced-pipeline"
    priority: 1  # High priority for advanced features
    schedule_type: "comprehensive_schedule"  # Every 2 hours during market hours
    tags:
      - features
      - production
      - comprehensive
      - phase3
      - subprocess
      - reliable
      - advanced
      - 90-features
    expected_runtime_minutes: 20  # ~4s per symbol * 100 symbols
    alert_threshold_hours: 3  # Important - alert if fails


  # Production Yahoo Data Collection
  yahoo-production-data-collection:
    name: "yahoo-production-data-collection"
    display_name: "Yahoo Finance Data Collection"
    description: "Production Yahoo Finance data collection (3-day optimized) - runs hourly during market hours"
    category: "data-collection"
    priority: 2  # Supporting production deployment
    schedule_type: "market_hours"
    tags:
      - yahoo
      - production
      - hourly
      - optimized
      - data-collection
    expected_runtime_minutes: 8  # 5-10 minutes for data collection
    alert_threshold_hours: 2  # Critical - alert quickly if fails

# Dashboard display settings
dashboard:
  # Which deployments to show on main dashboard (by priority)
  primary_deployments:
    - comprehensive-feature-engineering-production-subprocess
    - yahoo-production-data-collection
  
  # Maximum number of deployments to show
  max_visible_deployments: 2
  
  # Refresh intervals (in seconds)
  refresh_intervals:
    pipeline_status: 30
    system_health: 60
    data_freshness: 45

# Schedule type definitions for next run calculation
schedule_types:
  market_hours:
    cron: "0 9-16 * * 1-5"
    timezone: "America/New_York"
    description: "Hourly during market hours (9 AM - 4 PM EST, weekdays)"
  
  
  comprehensive_schedule:
    cron: "10 9-15/2 * * 1-5"
    timezone: "America/New_York"
    description: "Every 2 hours during market hours (9:10 AM, 11:10 AM, 1:10 PM, 3:10 PM EST, weekdays)"

# Feature Engineering Categories Reference
# This documents what's included in each phase for monitoring purposes
feature_categories:
  phase_1_foundation:
    count: 13
    description: "Basic price and time features"
    includes: ["returns", "log_returns", "price_ratios", "time_features"]
    
  phase_2_core_technical:
    count: 23
    description: "Core technical indicators"
    includes: ["moving_averages", "volatility_measures", "bollinger_bands", "macd", "atr"]
    
  phase_3_advanced:
    count: 54
    description: "Advanced ML-ready features"
    includes: ["volume_indicators", "rsi_multi_timeframe", "intraday_features", "lagged_features", "rolling_statistics"]
    
  total_comprehensive:
    count: 90
    description: "Complete feature set for advanced ML analysis"
    database_table: "feature_engineered_data"
    version: "3.0"